[package]
name = "pmtk"
version = "0.3.0"
edition = "2024"
authors = ["Jonathan D. Baker <jonathan@ardent.tech>"]
description = "A no-std implementation of PMTK (rev. A11) definitions."
keywords = ["embedded", "pmtk", "gps"]
categories = ["embedded", "no-std"]
repository = "https://github.com/ardentTech/pmtk"
license = "MIT OR Apache-2.0"
exclude = ["CHANGELOG.md"]
readme = "README.md"

[dependencies]
heapless = "0.9.3"
nom = { version = "8.0.0", default-features = false, features = ["alloc"] }
defmt = { version = "1.1.1", optional = true }

[features]
default = []
defmt = ["dep:defmt"]
mt3339 = []